---
title: "troubleshooting_fst_angsd"
author: "kira delmore"
date: "july 17 2017"
output: 
  html_document: 
    keep_md: yes
---

### load libraries
```{r}
setwd("~/Documents/Projects/comparative_analysis/troubleshoot_fst/")
library(plot3D)
suppressWarnings(library(plot3D))
suppressWarnings(library(ggplot2))
suppressWarnings(library(grid))
```

### load windowed (100kb) fst and limit to chr 10
```{r}
dat_unfolded <- read.csv("comparative_datasets_combined_100.csv")
chr10_unfolded <- subset(dat_unfolded,dat_unfolded$chr=="Chromosome_10")
dat_folded <- read.csv("comparative_datasets_combined_100_fold1.csv")
chr10_folded <- subset(dat_folded,dat_folded$chr=="Chromosome_10")
```

### plot fst along chromosome for all pairs starting with unfolded
```{r scatterplot, fig.width=12, fig.height=8, warning=FALSE, message=FALSE, echo=FALSE}
chr10_unfolded.stacked <- data.frame(chr10_unfolded$midpos,stack(chr10_unfolded, select=c("fst_fly","fst_will","fst_crow","fst_black","fst_green","fst_blue")))

chr10_unfolded.stacked$ind <- gsub("fst_fly","flycatcher",chr10_unfolded.stacked$ind)
chr10_unfolded.stacked$ind <- gsub("fst_will","willow",chr10_unfolded.stacked$ind)
chr10_unfolded.stacked$ind <- gsub("fst_crow","crow",chr10_unfolded.stacked$ind)
chr10_unfolded.stacked$ind <- gsub("fst_black","blackcap",chr10_unfolded.stacked$ind)
chr10_unfolded.stacked$ind <- gsub("fst_green","greenish",chr10_unfolded.stacked$ind)
chr10_unfolded.stacked$ind <- gsub("fst_blue","blue/gold",chr10_unfolded.stacked$ind)
  
chr10_unfolded.stacked$ind <- factor(chr10_unfolded.stacked$ind,levels=c("crow","greenish","willow","blackcap","blue/gold","stonechat","flycatcher","thrush"))

g=ggplot(chr10_unfolded.stacked,aes(chr10_unfolded.midpos,values,colour=factor(ind)))+
    
   geom_line()+
    labs(x="bp along chromosome",y=expression(italic(F[ST])))+
    theme_bw(base_size=20)+
    theme(
      axis.title.x = element_text(vjust=-2,size=20),
      axis.title.y = element_text(vjust=1.25,size=20,face="italic"),
      axis.text.x = element_text(colour="black",size=12),
      axis.text.y = element_text(colour="black",size=12),
      plot.title = element_text(size = 20, face = "bold"),
      legend.position="none",
      strip.background = element_rect(fill = 'white', colour="black"),
      strip.text.y = element_text(size=10),
      #panel.spacing = unit(2, "lines"),
      #plot.margin = unit(c(2, 2, 2, 2), "cm"),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(), 
      panel.background = element_rect(fill="white",colour="black"),
      axis.line = element_line(colour = "black"),
      panel.border = element_rect(colour = "black", fill=NA),
      panel.spacing = unit(0.5, "lines"))+
    ggtitle("fst_chr10_unfolded")+
    facet_grid(ind ~.,scales="free")
  
  print(g)

chr10_folded.stacked <- data.frame(chr10_folded$midpos,stack(chr10_folded, select=c("fst_fly","fst_will","fst_crow","fst_black","fst_green","fst_blue")))

chr10_folded.stacked$ind <- gsub("fst_fly","flycatcher",chr10_folded.stacked$ind)
chr10_folded.stacked$ind <- gsub("fst_will","willow",chr10_folded.stacked$ind)
chr10_folded.stacked$ind <- gsub("fst_crow","crow",chr10_folded.stacked$ind)
chr10_folded.stacked$ind <- gsub("fst_black","blackcap",chr10_folded.stacked$ind)
chr10_folded.stacked$ind <- gsub("fst_green","greenish",chr10_folded.stacked$ind)
chr10_folded.stacked$ind <- gsub("fst_blue","blue/gold",chr10_folded.stacked$ind)
  
chr10_folded.stacked$ind <- factor(chr10_folded.stacked$ind,levels=c("crow","greenish","willow","blackcap","blue/gold","stonechat","flycatcher","thrush"))

g=ggplot(chr10_folded.stacked,aes(chr10_folded.midpos,values,colour=factor(ind)))+
    
   geom_line()+
    labs(x="bp along chromosome",y=expression(italic(F[ST])))+
    theme_bw(base_size=20)+
    theme(
      axis.title.x = element_text(vjust=-2,size=20),
      axis.title.y = element_text(vjust=1.25,size=20,face="italic"),
      axis.text.x = element_text(colour="black",size=12),
      axis.text.y = element_text(colour="black",size=12),
      plot.title = element_text(size = 20, face = "bold"),
      legend.position="none",
      strip.background = element_rect(fill = 'white', colour="black"),
      strip.text.y = element_text(size=10),
      #panel.spacing = unit(2, "lines"),
      #plot.margin = unit(c(2, 2, 2, 2), "cm"),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(), 
      panel.background = element_rect(fill="white",colour="black"),
      axis.line = element_line(colour = "black"),
      panel.border = element_rect(colour = "black", fill=NA),
      panel.spacing = unit(0.5, "lines"))+
    ggtitle("fst_chr10_folded")+
    facet_grid(ind ~.,scales="free")
  
  print(g)
```

### take closer look at flycatchers, summarizing fst and plotting histograms
```{r}
hist(chr10_unfolded$fst_fly)
summary(chr10_unfolded$fst_fly)
hist(chr10_folded$fst_fly)
summary(chr10_folded$fst_fly)
```

### continue with flycatchers looking at sfs for chr10 starting with unfolded
```{r}
ANGSD.2D.SFS.UNFOLDED <- scan("CM001999.1_collared.pied.ml.unfolded")
ANGSD.2D.SFS.FOLDED <- scan("CM001999.1_collared.pied.ml.folded")
nPop1=79
nPop2=79

ANGSD.2D.SFS.UNFOLDED <- t(matrix(ANGSD.2D.SFS.UNFOLDED, nrow=((nPop1*2)+1), ncol=((nPop2*2)+1)))
ANGSD.2D.SFS.UNFOLDED[1,1] <- 0
ANGSD.2D.SFS.UNFOLDED[nrow(ANGSD.2D.SFS.UNFOLDED),ncol(ANGSD.2D.SFS.UNFOLDED)] <- 0
hist3D(x = seq(0,1,length.out = nrow(ANGSD.2D.SFS.UNFOLDED)), y = seq(0,1,length.out=ncol(ANGSD.2D.SFS.UNFOLDED)), ANGSD.2D.SFS.UNFOLDED, cex.lab=1.2, xlab="collared",ylab="pied",zlab="SFS", main=paste("2D-SFS_chr10_unfolded"),pin=c(10,0), cex.main=1.4, zlim=c(0,max(ANGSD.2D.SFS.UNFOLDED)))

ANGSD.2D.SFS.FOLDED <- t(matrix(ANGSD.2D.SFS.FOLDED, nrow=nPop1+1, ncol=nPop2+1))
ANGSD.2D.SFS.FOLDED[1,1] <- 0
ANGSD.2D.SFS.FOLDED[nrow(ANGSD.2D.SFS.FOLDED),ncol(ANGSD.2D.SFS.FOLDED)] <- 0
hist3D(x = seq(0,1,length.out = nrow(ANGSD.2D.SFS.FOLDED)), y = seq(0,1,length.out=ncol(ANGSD.2D.SFS.FOLDED)), ANGSD.2D.SFS.FOLDED, cex.lab=1.2, xlab="collared",ylab="pied",zlab="SFS", main=paste("2D-SFS_chr10_folded"),pin=c(10,0), cex.main=1.4, zlim=c(0,max(ANGSD.2D.SFS.FOLDED)))
```